export const tables: Array<{ id: string; capacity: number }> = [
    { id: 'one', capacity: 2 },
    { id: 'two', capacity: 2 },
    { id: 'three', capacity: 2 },
    { id: 'four', capacity: 2 },
    { id: 'five', capacity: 2 },
    { id: 'six', capacity: 2 },
    { id: 'seven', capacity: 2 },
    { id: 'eight', capacity: 3 },
    { id: 'nine', capacity: 3 },
    { id: 'ten', capacity: 3 },
    { id: 'eleven', capacity: 3 },
    { id: 'twelve', capacity: 3 },
    { id: 'thirteen', capacity: 3 },
    { id: 'fourteen', capacity: 6 },
    { id: 'fifteen', capacity: 6 },
    { id: 'sixteen', capacity: 6 },
];
