export const tables: Array<{ id: number; capacity: number }> = [
    { id: 1, capacity: 2 },
    { id: 2, capacity: 2 },
    { id: 3, capacity: 2 },
    { id: 4, capacity: 2 },
    { id: 5, capacity: 2 },
    { id: 6, capacity: 2 },
    { id: 7, capacity: 2 },
    { id: 8, capacity: 3 },
    { id: 9, capacity: 3 },
    { id: 10, capacity: 3 },
    { id: 11, capacity: 3 },
    { id: 12, capacity: 3 },
    { id: 13, capacity: 3 },
    { id: 14, capacity: 6 },
    { id: 15, capacity: 6 },
    { id: 16, capacity: 6 },
];
