export enum UserActions {
    SET_MODAL = 'SET_MODAL',
    SET_CURRENT_USER = 'SET_CURRENT_USER',
    ADD_NEW_USER = 'ADD_NEW_USER',
    ADD_NEW_ORDER = 'ADD_NEW_ORDER',
    ADD_CURRENT_RESTAURANT = 'ADD_CURRENT_RESTAURANT',
    REMOVE_USER = 'REMOVE_USER',
    REMOVE_ORDER = 'REMOVE_ORDER',
    FETCH_ORDERS = 'FETCH_ORDERS',
}

export enum AuthActions {
    IS_LOGGED = 'IS_LOGGED',
}
